### ISSUE TITLE
Error during uninstall

### ISSUE THREAD

**Issue by cgars** [G-Node/GinUI#52]
During uninstall, the wizard complains that GinCLiService and Windows-Explorer is still using files that the uninstaller needs to remove.

**Comment by The-E** [comment]
This is an error that's going to be a bit difficult to resolve.
What's happening is this: When msiexec tries to execute our uninstaller, it goes through a validation phase where it checks if any of the files it's supposed to uninstall are currently open. This, of course, is the case if any of the components in thos package are currently running. 
Unfortunately, Visual Studio Installer projects are not able to override this validation phase (or schedule proper shutdowns before the validation phase starts); this is only possible using third-party tools, which would require a complete rebuild of the installer in them. 

The workaround here is to just let the installer continue: It includes code that will safely uninstall everything.

**Comment by The-E** [comment]
The current installer will only require a restart of Explorer if the shell extension has been loaded; this I think is sufficient to resolve this.
