### ISSUE TITLE
Installation notice for Dokan

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/GinUI#82]
The window "Installation Complete [...] Click Close to exit. Install Dokan" should explain that Dokan is necessary (e.g. "GIN Windows client has been successfully installed. Additionally, the client needs the Dokan software ...").

This would certainly go into release notes and installation instructions, but it should probably be explained on the installer as well for people who don't read installation instructions.

**Comment by JiriVanek** [comment]
Presence of Dokan and Gin-cli is checked at program startup. If Dokan is missing user is prompted to install it. For missing Gin-cli user is asked to reinstall application.
