### ISSUE TITLE
Error: Broken Links

### ISSUE THREAD

**Issue by iksiddhanthrao** [G-Node/GinUI#88]
Last week or so, an error popped up related to the Dokan library (it was in German and it didn't strike me to screenshot it and the moment) but I clicked Weiter and continued my work. Things turned out fine.

However, when I restarted the system I discovered that all the links from the Mountpoint Directory to the Checkout Directory were broken. 

I deleted all the data and reinstalled the app as suggested earlier and it seemed fine until I got the following error:  

![scn5](https://user-images.githubusercontent.com/37540700/38877147-56316a60-425e-11e8-9966-c8d2dd328c6d.PNG)

Here is the logfile:

[gin.log](https://github.com/G-Node/GinUI/files/1920302/gin.log)

I must also mention that I had some trouble with Dokan during the reinstallation with an error saying "Failed to install MSI package" but that was sorted as soon as I tried it again.

**Comment by achilleas-k** [comment]
Fixed in #93.
