### ISSUE TITLE
While GinUI installed Windows context menu is not working

### ISSUE THREAD

**Issue by JiriVanek** [G-Node/GinUI#92]
After installation of GinUI is Context menu in Windows incredibly slow, after disabling GinShellExtensionClass works like a charm again.
Windows 10 Professional 64-bit.
Same behavior on two different computers.

**Comment by achilleas-k** [comment]
That seems bad. Do you mean that it takes very long for the context menu to appear when right clicking on a file?
Does it happen everywhere, or only inside GIN repositories?

**Comment by JiriVanek** [comment]
Exactly. it tooks several minutes to menu opens... And it occurs on any file / folder or desktop even outside GIN repositories.

**Comment by achilleas-k** [comment]
Ok. Definitely bad. Thanks for reporting.

**Comment by achilleas-k** [comment]
Issue was caused by GIN service being in a faulty state. A restart fixed it and we haven't managed to reproduce. Closing
